// Trimmed dataset extracted from data/morning_report_2026-04-28.json
// + supporting summaries. Keeps ticker fields the dashboard actually renders.

window.REPORT = {
  meta: {
    report_date: "2026-04-28",
    market_date: "2026-04-27",
    timezone: "SGT",
  },
  benchmarks: {
    SPY:   { price: 715.17, chg: 0.16,  unit: "S&P 500" },
    QQQ:   { price: 664.23, chg: 0.09,  unit: "Nasdaq 100" },
    DXY:   { price: 98.53,  chg: 0.10,  unit: "Dollar index" },
    WTI:   { price: 97.21,  chg: 1.98,  unit: "Crude oil" },
    Gold:  { price: 4687.4, chg: -1.11, unit: "Gold" },
    VIX:   { price: 18.02,  chg: -3.58, unit: "Fear gauge", inverse: true },
    US10Y: { price: 4.34,   chg: 0.60,  unit: "10-yr yield" },
    SOXX:  { price: 455.41, chg: -1.35, unit: "Semis ETF" },
  },
  stance: "Deeply defensive — maximum CAUTION posture",
  stance_plain: "Stay on the sidelines. Thirteen of sixteen names are in CAUTION; this week's Big Tech earnings are the next hinge.",
  signal_counts: { BUY: 0, ACCUMULATE: 0, WATCH: 1, HOLD: 2, CAUTION: 13 },
  macro_summary:
    "Markets ground sideways Monday with SPY +0.16% near record highs. The dominant story remains the Hormuz crisis (week 8) — Iran reaffirmed Sunday the Strait will not return to normal, sending WTI up 2%. Wednesday's triple print (AMZN, GOOG, MSFT) is the single near-term inflection: the market is treating it as a $1.7T capex thesis test. US-China tech restrictions continue to escalate — new Entity-List expansions could land as soon as June.",
  geopolitical: {
    probabilities: { base: 52, optimistic: 22, pessimistic: 18, wildcard: 8 },
    active_risks: [
      { tag: "Hormuz", text: "Iran-Hormuz blockade enters week 8. Tehran declared Sunday the Strait will 'under no circumstances' return to its previous state; peace talks have stalled." },
      { tag: "US-China", text: "New Entity List expansions targeting CXMT and SMIC subsidiaries could come into force as early as June, threatening further semi supply-chain bifurcation." },
      { tag: "Trade truce", text: "May 9-12 US-China summit truce is fraying — both sides accuse the other of breaking the deal." },
      { tag: "Logistics", text: "East-west shipping has reverted to Cape detours; +10-14 days transit, structural cost inflation persisting." },
    ],
    portfolio_action:
      "Maintain defensive positioning with no new entries on extended names; April 30 earnings (AMZN, GOOG, MSFT, DBS) are the single most important near-term signal.",
  },
  events: [
    { date: "2026-04-30", impact: "HIGH",   ticker: "AMZN", text: "Q1 Earnings — capex guidance is the read-through ($200B AI commitment reaffirm vs. moderate)." },
    { date: "2026-04-30", impact: "HIGH",   ticker: "GOOG", text: "Q1 Earnings — Gemini monetisation, TPU v7 cloud revenue, AI capex stance." },
    { date: "2026-04-30", impact: "HIGH",   ticker: "MSFT", text: "Q1 Earnings — Azure ex-OpenAI growth, non-OpenAI RPO, OpenAI exclusivity loss impact." },
    { date: "2026-04-30", impact: "MEDIUM", ticker: "DBS",  text: "Q1 Earnings — NIM trajectory and dividend guidance under dual compression." },
    { date: "2026-04-30", impact: "MEDIUM", ticker: "—",    text: "Employment Cost Index (Q1) — sticky wage inflation read-through for the Fed." },
    { date: "2026-05-05", impact: "HIGH",   ticker: "PLTR", text: "Q1 Earnings — defense contract conversion; $10B Army IDIQ task order update." },
    { date: "2026-05-05", impact: "MEDIUM", ticker: "—",    text: "JOLTS (March) — labour-market tightness for Fed hawkish floor." },
    { date: "2026-05-07", impact: "HIGH",   ticker: "FOMC", text: "Rate decision — hawkish hold expected; pivot language would re-rate Singapore banks and tech multiples." },
  ],
  // Watchlist (16 tickers). cluster, currency, signal, prev_signal, key metrics, plain-english + technical rationale.
  watchlist: [
    {
      ticker: "ASML", display: "ASML", name: "ASML Holding", cluster: "Semis", ccy: "USD",
      price: 1432.44, chg: -1.72, m1: 7.74,
      signal: "WATCH", prev: "WATCH",
      vs_sma50: 2.05, rsi: 51.8, rr: 2.0,
      pe_fwd: 30.1, peg: 2.25, rev_g: 13.2,
      block: null,
      next_event: "Earnings — May 14",
      headline: "Cleanest semi setup; just slightly extended.",
      action: "Watch for entry",
      plain: "The healthiest-looking name on the watchlist. Not a buy yet — wait for a $30–50 dip toward the $1,382–1,403 zone, then size in.",
      tech: "2.05% above SMA50 (upper edge of clean-entry zone), RSI 51.8 neutral, R:R 2.0:1 to $1,491. Wide-stop R:R only 0.5:1 so headline ratio leans on a tight SMA50 stop. Volume below average. MATCH Act / TSMC A13 are live tail-risks.",
    },
    {
      ticker: "D05_SI", display: "D05.SI", name: "DBS Group", cluster: "SG Banks", ccy: "SGD",
      price: 57.02, chg: 0.39, m1: 1.20,
      signal: "HOLD", prev: "HOLD",
      vs_sma50: 1.26, rsi: 52.5, rr: 3.1,
      pe_fwd: 13.8, peg: 4.03, rev_g: -3.3,
      block: null,
      next_event: "Earnings — Apr 30",
      headline: "Going nowhere fast while NIM pressure persists.",
      action: "Hold off",
      plain: "Earnings on Wednesday and analyst forecasts of an 8.8% earnings decline make this an unattractive entry. Wait for US 10-yr yield to break below 4.20%.",
      tech: "Headline 3.1:1 R:R rests on a tight 1.2% SMA50 stop. Wide-stop R:R is just 0.55:1. RSI 52.5 neutral. Singapore-bank reset gates not met (US10Y 4.34% > 4.20% trigger; MAS S$NEER unchanged).",
    },
    {
      ticker: "O39_SI", display: "O39.SI", name: "OCBC", cluster: "SG Banks", ccy: "SGD",
      price: 21.80, chg: 0.79, m1: 3.73,
      signal: "HOLD", prev: "ACCUMULATE",
      vs_sma50: 3.12, rsi: 55.0, rr: 1.1,
      pe_fwd: 12.2, peg: 2.86, rev_g: 6.5,
      block: null,
      next_event: "Earnings — May 8",
      headline: "Best-of-cluster — but the entry maths don't work.",
      action: "Hold off",
      plain: "Downgraded from ACCUMULATE: risk-versus-reward is no longer favourable. Revisit on a pullback to S$21.59 or a sub-4.20% US 10-yr.",
      tech: "Wide-stop R:R 0.53:1 — gate G2 fails. SMA50 rising at S$21.14. Best Singapore bank fundamentals (6.5% revenue growth, only YoY profit grower). PEG 2.86 elevated.",
    },
    {
      ticker: "U11_SI", display: "U11.SI", name: "UOB", cluster: "SG Banks", ccy: "SGD",
      price: 36.01, chg: 0.31, m1: -0.36,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: -0.68, rsi: 42.5, rr: 1.1,
      pe_fwd: 10.0, peg: 0.97, rev_g: -1.8,
      block: null,
      next_event: "Earnings — May 7",
      headline: "Slipped back below a falling SMA50.",
      action: "Avoid",
      plain: "Cheap can get cheaper when earnings are deteriorating. Wait for a clean reclaim of the 50-day average on volume.",
      tech: "Below SMA50 (S$36.26), and the SMA50 is itself declining. RSI 42.5. Wide-stop R:R 0.56:1. Dual NIM compression channels intact. Earnings May 7 — binary risk in 9 days.",
    },
    {
      ticker: "NVDA", display: "NVDA", name: "Nvidia", cluster: "Semis", ccy: "USD",
      price: 216.61, chg: 4.08, m1: 26.49,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 16.7, rsi: 76.3, rr: 0.3,
      pe_fwd: 19.3, peg: 0.74, rev_g: 73.2,
      block: "Extended +16.7% above 50-day average — RSI 76 confirms overbought.",
      next_event: "Earnings — May 21",
      headline: "Fundamentally compelling, technically too expensive.",
      action: "Avoid for now",
      plain: "The business is strong (73% revenue growth, 96% earnings growth) but the stock has run too hot. Wait for a pullback toward $177–185.",
      tech: "Hard-blocked: +16.7% above SMA50, RSI 76.3, R:R 0.3:1. Volume confirmed Monday's move. Q1 FY27 guide $78B implies Blackwell shipping ahead of model. Fragility gate active until May 21 print.",
    },
    {
      ticker: "AMD", display: "AMD", name: "AMD", cluster: "Semis", ccy: "USD",
      price: 334.63, chg: -4.03, m1: 64.22,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 49.29, rsi: 80.2, rr: 0.2,
      pe_fwd: 30.4, peg: 1.03, rev_g: 34.1,
      block: "Extreme +49% extension — no trend exception applies.",
      next_event: "Earnings — May 6",
      headline: "Real story, ran too far too fast.",
      action: "Avoid",
      plain: "Up 64% in a month after the Meta GPU framework. Cathie Wood's ARK has been selling. Needs to consolidate significantly before the trade makes sense.",
      tech: "+49% above SMA50, RSI 80.2, R:R 0.2:1. Meta MI450 framework still contingent on benchmarks. SMA50 33% below price — pullback to SMA50 is crash-level.",
    },
    {
      ticker: "INTC", display: "INTC", name: "Intel", cluster: "Semis", ccy: "USD",
      price: 84.99, chg: 2.74, m1: 92.72,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 64.07, rsi: 83.3, rr: 0.1,
      pe_fwd: 57.7, peg: 1.36, rev_g: 7.2,
      block: "Most extreme on watchlist — +64% above SMA50.",
      next_event: "Earnings — Jul 24",
      headline: "Manufacturing progress already massively priced in.",
      action: "Avoid",
      plain: "Up 93% in a month. 18A node still has zero confirmed external customers. FCF is negative. Avoid until major consolidation.",
      tech: "+64% above SMA50, RSI 83.3, R:R 0.1:1. Forward PE 57.7x — 117% above semis cluster median. FCF yield -1.94%. 14A traction with Tesla doesn't validate 18A.",
    },
    {
      ticker: "MU", display: "MU", name: "Micron", cluster: "Semis", ccy: "USD",
      price: 524.56, chg: 6.11, m1: 47.63,
      signal: "CAUTION", prev: "HOLD",
      vs_sma50: 25.82, rsi: 73.2, rr: 0.2,
      pe_fwd: 5.2, peg: 0.29, rev_g: 196.3,
      block: "Triggered extreme-extension hard block on Monday's +6%.",
      next_event: "Earnings — Jun 25",
      headline: "Best fundamental story, wrong entry.",
      action: "Avoid for now",
      plain: "Forward PE of 5.2x and PEG 0.29 with 196% revenue growth — the fundamentals are extraordinary. But up 48% in a month, it needs to come in 15–20%.",
      tech: "+25.8% above SMA50, RSI 73.2. PEG 0.29 (growth massively outpaces multiple). HBM demand structurally tight through 2026-27. R:R 0.2:1 from here.",
    },
    {
      ticker: "TSM", display: "TSM", name: "TSMC", cluster: "Semis", ccy: "USD",
      price: 404.98, chg: 0.39, m1: 24.19,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 13.34, rsi: 69.1, rr: 0.4,
      pe_fwd: 21.0, peg: 1.30, rev_g: 35.1,
      block: "+13.3% above SMA50; sustained-trend exception not yet met.",
      next_event: "Earnings — Jul 17",
      headline: "Cheap relative to its growth — but extended.",
      action: "Avoid for now",
      plain: "AI buildout depends on TSMC's CoWoS packaging. Forward PE 21x is below cluster median. But needs to consolidate toward $360.",
      tech: "+13.3% above SMA50, RSI 69.1, R:R 0.4:1. CoWoS scaling 80K → 120-130K wafers/mo by end-2026; NVDA has booked >50%. Forward PE 21% below semis cluster median.",
    },
    {
      ticker: "AMZN", display: "AMZN", name: "Amazon", cluster: "BigTech", ccy: "USD",
      price: 261.12, chg: -1.17, m1: 25.82,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 18.76, rsi: 75.9, rr: 0.3,
      pe_fwd: 27.6, peg: 1.91, rev_g: 13.6,
      block: "+18.8% above SMA50, RSI 75.9.",
      next_event: "Earnings — Apr 30 (in 2 days)",
      headline: "Wait for the print. Period.",
      action: "Avoid before earnings",
      plain: "Earnings Wednesday on top of an already-extended technical setup. Capex commitment ($200B) reaffirmation vs. moderation is the question.",
      tech: "Hard-blocked. R:R 0.3:1. Polymarket actively debating 2026 capex. Analyst consensus only +5% earnings growth despite revenue strength — capex-to-earnings conversion in question.",
    },
    {
      ticker: "GOOG", display: "GOOG", name: "Alphabet", cluster: "BigTech", ccy: "USD",
      price: 348.52, chg: 1.97, m1: 24.14,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 12.69, rsi: 72.6, rr: 0.0,
      pe_fwd: 25.8, peg: 2.34, rev_g: 18.0,
      block: "Within 0.4% of nearest resistance with earnings imminent.",
      next_event: "Earnings — Apr 30 (in 2 days)",
      headline: "Effectively zero margin of safety.",
      action: "Avoid before earnings",
      plain: "Trading 0.4% below resistance with binary earnings in two days. The TPU v7 thesis is alive but no entry before the print.",
      tech: "+12.7% above SMA50, RSI 72.6. R:R 0.0:1 — resistance at $349.90 is 0.4% above. PEG 2.34 expensive for an 18% revenue grower.",
    },
    {
      ticker: "MSFT", display: "MSFT", name: "Microsoft", cluster: "BigTech", ccy: "USD",
      price: 424.82, chg: 0.22, m1: 16.08,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 7.70, rsi: 63.6, rr: 2.1,
      pe_fwd: 22.5, peg: 1.34, rev_g: 16.7,
      block: "+7.7% above SMA50; 10 sessions above (need 30 for trend exception).",
      next_event: "Earnings — Apr 30 (in 2 days)",
      headline: "OpenAI exclusivity loss is the new wildcard.",
      action: "Avoid before earnings",
      plain: "Headline R:R 2.1:1 looks attractive, but the OpenAI agreement amendment changes the story. Wait for the print to read Azure ex-OpenAI growth.",
      tech: "Hard-blocked: 10 sessions above SMA50 < 30-session trend gate. Wide-stop R:R 1.48:1 (under 1.5 threshold). Forward PE 22.5x is 15.7% below cluster median.",
    },
    {
      ticker: "AVGO", display: "AVGO", name: "Broadcom", cluster: "Semis", ccy: "USD",
      price: 418.20, chg: -0.43, m1: 35.16,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 22.01, rsi: 74.3, rr: 0.3,
      pe_fwd: 23.1, peg: 0.92, rev_g: 29.5,
      block: "+22% extreme extension. Hit ATH and joined the $2T market-cap club.",
      next_event: "Earnings — Jun 5",
      headline: "Hit a $2T market cap. Now needs to breathe.",
      action: "Avoid for now",
      plain: "Custom ASIC thesis (Google TPU, Meta training chips, OpenAI/ByteDance pipeline) is high-conviction. But a 15–20% pullback is needed.",
      tech: "+22% above SMA50, RSI 74.3, R:R 0.3:1. Forward PE 23.1x is below cluster median. PEG 0.92 reasonable. Custom ASIC + AI optics pipeline intact.",
    },
    {
      ticker: "LITE", display: "LITE", name: "Lumentum", cluster: "AI Optics", ccy: "USD",
      price: 245.50, chg: -0.85, m1: 28.40,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 16.0, rsi: 72.0, rr: 0.4,
      pe_fwd: 38.0, peg: 1.55, rev_g: 22.0,
      block: "+16% above SMA50.",
      next_event: "Earnings — May 6",
      headline: "Wait for the print or a pullback to $800-equivalent support.",
      action: "Avoid for now",
      plain: "AI optics name with NVDA $2B strategic stake. Negative FCF yield. May 6 earnings approaching.",
      tech: "+16% above SMA50, RSI 72. NVDA strategic investment partner alongside COHR. FCF negative. Wait for May 6 print.",
    },
    {
      ticker: "PLTR", display: "PLTR", name: "Palantir", cluster: "Defense AI", ccy: "USD",
      price: 184.20, chg: 1.20, m1: 18.50,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 28.0, rsi: 71.5, rr: 0.3,
      pe_fwd: 76.8, peg: 3.20, rev_g: 32.0,
      block: "Distorted R:R; valuation extreme.",
      next_event: "Earnings — May 5",
      headline: "76.8x forward PE — wait for the print.",
      action: "Avoid before earnings",
      plain: "Defense AI beneficiary of Hormuz crisis spending. Earnings May 5; wait for the print and a meaningful pullback.",
      tech: "Forward PE 76.8x. R:R distorted. $10B Army IDIQ task-order update is the catalyst. Technical breakout above $144.86 SMA50 possible on a beat.",
    },
    {
      ticker: "WRD", display: "WRD", name: "WeRide", cluster: "China Tech", ccy: "USD",
      price: 13.20, chg: 0.50, m1: 12.00,
      signal: "CAUTION", prev: "CAUTION",
      vs_sma50: 12.0, rsi: 65.0, rr: 0.1,
      pe_fwd: null, peg: null, rev_g: 88.0,
      block: "Resistance clustered 2–4% above current.",
      next_event: "Earnings — May 28",
      headline: "ADR / delisting risk is a standing concern.",
      action: "Avoid",
      plain: "Resistance just 2–4% above. ADR and US-listing risk make the upside unattractive vs. the downside.",
      tech: "+12% above SMA50, R:R 0.1:1. Resistance clustered 2-4% overhead. Standing US-listing/ADR risk on China names.",
    },
  ],
  watchlist_candidates: [
    { ticker: "COHR", name: "Coherent Corp",  note: "NVDA $2B strategic investment partner alongside LITE — same AI optics thesis. Add if LITE May 6 confirms revenue traction or COHR pulls back 10-12%." },
    { ticker: "LRCX", name: "Lam Research",   note: "Semi-equipment name linked to INTC 18A ramp and MU HBM capex cycle. Becomes actionable if INTC 18A yield drives etch-tool orders at next LRCX print." },
  ],
  // Computed signal-change list (today vs yesterday)
  changes: [
    { ticker: "O39.SI", from: "ACCUMULATE", to: "HOLD",    direction: "down", note: "R:R gate failed — wide-stop ratio 0.53:1." },
    { ticker: "MU",     from: "HOLD",       to: "CAUTION", direction: "down", note: "Triggered extreme-extension block after +6% Monday." },
  ],
};
